version: 0.0      # AppSpec version for EC2/On-premises
os: linux         # Target operating system

files:            # File copy instructions
  - source: /     # Copy from root of artifact
    destination: /home/ec2-user/my-node-app  # Destination on target server
    overwrite: yes  # Replace existing files

permissions:      # Set file/directory permissions
  - object: /home/ec2-user/my-node-app
    pattern: "**"   # Apply to all files
    owner: ec2-user # File owner
    group: ec2-user # File group

hooks:           # Deployment lifecycle events
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300      # 5 minutes timeout
      runas: ec2-user   # Run as this user
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
