version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running tests...
      - npm test

  build:
    commands:
      - echo Build started on `date`
      - echo Creating deployment package...

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*
    - .git/**/*
